; """
; pytest.ini controls pytest logging behavior.

; pytest is acting like a temporary logging configuration for tests.
; It creates logging handlers and controls how logs are displayed.

; -v:
;     Verbose test output.
;     Shows full test names and status.

; -s:
;     Disable stdout/stderr capture.
;     Shows print(), stdout, and stderr immediately.

; log_cli:
;     Enable live logging output during test execution.

; log_cli_level:
;     Minimum logging level that pytest displays in the terminal.
; """

[pytest]

# Display logs while tests are running
log_cli = true

# Show DEBUG, INFO, WARNING, ERROR, CRITICAL logs
log_cli_level = DEBUG

# Automatically apply these command-line options
addopts = -v -s